#!/usr/bin/env python3
"""
Generate poi_mapping.lua from category_mapping.json
This script converts the JSON category mapping into a Lua table for osm2pgsql
"""

import json
import sys
from pathlib import Path

def generate_lua_mapping(json_path: Path, output_path: Path):
    """Generate Lua mapping file from JSON category mapping"""
    
    with open(json_path) as f:
        data = json.load(f)
    
    categories = data.get('categories', [])
    
    with open(output_path, 'w') as f:
        f.write("-- Auto-generated POI mapping from category_mapping.json\n")
        f.write("-- DO NOT EDIT THIS FILE DIRECTLY\n\n")
        f.write("local poi_mapping = {\n")
        
        for i, category in enumerate(categories):
            class_name = category['class']
            matches = category['matches']
            
            f.write(f"  {{\n")
            f.write(f"    class = '{class_name}',\n")
            f.write(f"    matches = {{\n")
            
            for match in matches:
                f.write("      {")
                for j, pair in enumerate(match):
                    key, value = pair
                    if j > 0:
                        f.write(", ")
                    f.write(f"{{'{key}', '{value}'}}")
                f.write("},\n")
            
            f.write("    },\n")
            f.write("  },\n")
        
        f.write("}\n\n")
        f.write("return poi_mapping\n")
    
    print(f"Generated {output_path}")

if __name__ == '__main__':
    script_dir = Path(__file__).parent
    json_path = script_dir / 'category_mapping.json'
    output_path = script_dir / 'poi_mapping.lua'
    
    if not json_path.exists():
        print(f"Error: {json_path} not found", file=sys.stderr)
        sys.exit(1)
    
    generate_lua_mapping(json_path, output_path)
